// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";
import * as React from "react";

var input = CssJs.style([
      CssJs.padding2(CssJs.rem(0.8), CssJs.rem(1.1)),
      CssJs.backgroundColor(CssJs.hex(Theme.Colors.primary50)),
      CssJs.borderStyle(CssJs.none),
      CssJs.borderRadius(Theme.Radius.small),
      CssJs.color(CssJs.hex(Theme.Colors.neutral)),
      CssJs.outlineStyle(CssJs.none),
      CssJs.selector("::placeholder", [CssJs.color(CssJs.hex(Theme.Colors.neutral200))])
    ]);

var InputStyles = {
  input: input
};

function InputText(Props) {
  var className = Props.className;
  var placeholderOpt = Props.placeholder;
  var value = Props.value;
  var onChange = Props.onChange;
  var placeholder = placeholderOpt !== undefined ? placeholderOpt : "";
  var style = className !== undefined ? CssJs.merge([
          input,
          className
        ]) : input;
  return React.createElement("input", {
              className: style,
              placeholder: placeholder,
              value: value,
              onChange: onChange
            });
}

var make = InputText;

export {
  InputStyles ,
  make ,
  
}
/* input Not a pure module */
