// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";
import * as React from "react";

var inputStyle = CssJs.style([
      CssJs.padding2(CssJs.rem(0.8), CssJs.rem(1.1)),
      CssJs.backgroundColor(CssJs.hex(Theme.Colors.primary50)),
      CssJs.borderStyle(CssJs.none),
      CssJs.borderRadius(Theme.Radius.small),
      CssJs.color(CssJs.hex(Theme.Colors.neutral)),
      CssJs.selector("::placeholder", [CssJs.color(CssJs.hex(Theme.Colors.neutral200))])
    ]);

function InputText(Props) {
  var placeholderOpt = Props.placeholder;
  var value = Props.value;
  var onChange = Props.onChange;
  var placeholder = placeholderOpt !== undefined ? placeholderOpt : "";
  return React.createElement("input", {
              className: inputStyle,
              placeholder: placeholder,
              value: value,
              onChange: onChange
            });
}

var make = InputText;

export {
  inputStyle ,
  make ,
  
}
/* inputStyle Not a pure module */
