// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";
import * as React from "react";
import * as JsxUtils from "../../utils/JsxUtils.bs.js";

function button(block) {
  return CssJs.style([
              CssJs.padding2(CssJs.rem(0.8), CssJs.rem(1.6)),
              CssJs.width(block ? CssJs.pct(100.0) : CssJs.unset),
              CssJs.backgroundColor(CssJs.hex(Theme.Colors.primary300)),
              CssJs.borderStyle(CssJs.none),
              CssJs.borderRadius(Theme.Radius.small),
              CssJs.color(CssJs.hex(Theme.Colors.white)),
              CssJs.cursor(CssJs.pointer)
            ]);
}

var Styles = {
  button: button
};

function Button(Props) {
  var children = Props.children;
  var blockOpt = Props.block;
  var className = Props.className;
  var block = blockOpt !== undefined ? blockOpt : false;
  var style = className !== undefined ? CssJs.merge([
          button(block),
          className
        ]) : button(block);
  return React.createElement("button", {
              className: style
            }, JsxUtils.str(children));
}

var make = Button;

export {
  Styles ,
  make ,
  
}
/* CssJs Not a pure module */
