// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Text from "../Text.bs.js";
import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";
import * as React from "react";

function button(block) {
  return CssJs.style([
              CssJs.padding2(CssJs.rem(0.8), CssJs.rem(1.6)),
              CssJs.width(block ? CssJs.pct(100.0) : CssJs.unset),
              CssJs.backgroundColor(CssJs.hex(Theme.Colors.primary)),
              CssJs.borderStyle(CssJs.none),
              CssJs.borderRadius(Theme.Radius.small),
              CssJs.color(CssJs.hex(Theme.Colors.white)),
              CssJs.cursor(CssJs.pointer)
            ]);
}

function Button(Props) {
  var children = Props.children;
  var blockOpt = Props.block;
  var block = blockOpt !== undefined ? blockOpt : false;
  return React.createElement("button", {
              className: button(block)
            }, React.createElement($$Text.make, {
                  children: children
                }));
}

var make = Button;

export {
  button ,
  make ,
  
}
/* CssJs Not a pure module */
