// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as JsxUtils from "../../utils/JsxUtils.bs.js";
import * as TypographyStyles from "./TypographyStyles.bs.js";

function Typography$Title(Props) {
  var children = Props.children;
  var className = Props.className;
  var style = className !== undefined ? CssJs.merge([
          TypographyStyles.title,
          className
        ]) : TypographyStyles.text;
  return React.createElement("h1", {
              className: style
            }, JsxUtils.str(children));
}

var Title = {
  make: Typography$Title
};

function Typography$Text(Props) {
  var children = Props.children;
  var className = Props.className;
  var style = className !== undefined ? CssJs.merge([
          TypographyStyles.text,
          className
        ]) : TypographyStyles.text;
  return React.createElement("span", {
              className: style
            }, JsxUtils.str(children));
}

var $$Text = {
  make: Typography$Text
};

export {
  Title ,
  $$Text ,
  
}
/* CssJs Not a pure module */
