// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";

var title = CssJs.style([
      CssJs.color(CssJs.hex(Theme.Colors.neutral)),
      CssJs.fontSize(CssJs.rem(1.6)),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 700
          }),
      CssJs.letterSpacing({
            NAME: "rem",
            VAL: -0.08
          })
    ]);

var text = CssJs.style([
      CssJs.color(CssJs.hex(Theme.Colors.neutral200)),
      CssJs.letterSpacing({
            NAME: "rem",
            VAL: -0.04
          })
    ]);

export {
  title ,
  text ,
  
}
/* title Not a pure module */
