// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../components/Icon.bs.js";
import * as Link from "../components/Link.bs.js";
import * as Logo from "../components/Logo.bs.js";
import * as React from "react";
import * as JsxUtils from "../utils/JsxUtils.bs.js";

function Feed(Props) {
  return React.createElement("div", {
              className: "page page-feed"
            }, React.createElement("div", {
                  className: "top-bar"
                }, React.createElement(Logo.make, {}), React.createElement("ul", {
                      className: "nav"
                    }, React.createElement("li", {
                          className: "item"
                        }, React.createElement(Link.make, {
                              active: true,
                              children: JsxUtils.str("Home"),
                              menuItem: true,
                              to: "#"
                            })), React.createElement("li", {
                          className: "item"
                        }, React.createElement(Link.make, {
                              active: false,
                              children: JsxUtils.str("New article"),
                              menuItem: true,
                              to: "#"
                            })), React.createElement("li", {
                          className: "item"
                        }, React.createElement(Link.make, {
                              active: false,
                              children: JsxUtils.str("Settings"),
                              menuItem: true,
                              to: "#"
                            }))), React.createElement("div", {
                      className: "user-account"
                    }, React.createElement("span", undefined, JsxUtils.str("@username")), React.createElement("div", {
                          className: "figure"
                        }, React.createElement(Icon.make, {
                              variant: "person"
                            })))), React.createElement("div", {
                  className: "page-content"
                }), React.createElement("div", undefined));
}

var make = Feed;

export {
  make ,
  
}
/* Icon Not a pure module */
