// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "../components/link/Link.bs.js";
import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as Button from "../components/button/Button.bs.js";
import * as JsxUtils from "../utils/JsxUtils.bs.js";
import * as InputText from "../components/input/InputText.bs.js";
import * as Typography from "../components/typography/Typography.bs.js";
import * as InputPassword from "../components/input/InputPassword.bs.js";

var form = CssJs.style([
      CssJs.marginTop(CssJs.rem(2.0)),
      CssJs.display(CssJs.flexBox),
      CssJs.flexDirection(CssJs.column)
    ]);

var formMarginTop = CssJs.style([CssJs.marginTop(CssJs.rem(1.2))]);

var skip = CssJs.style([CssJs.marginTop(CssJs.rem(2.0))]);

var Styles = {
  form: form,
  formMarginTop: formMarginTop,
  skip: skip
};

function SignInPage(Props) {
  return React.createElement("div", {
              className: "sign-in-page"
            }, React.createElement("section", {
                  className: "banner-section"
                }, React.createElement("div", {
                      className: "brand"
                    }, JsxUtils.str("LIGHTNING ICON conduit")), React.createElement("div", {
                      className: "header"
                    }, JsxUtils.str("A place to share knoledge"), React.createElement("br", undefined), JsxUtils.str("Where good ideas find you")), React.createElement("div", {
                      className: "image"
                    }, JsxUtils.str("Image"))), React.createElement("section", {
                  className: "form-section"
                }, React.createElement("div", {
                      className: "box"
                    }, React.createElement(Typography.Title.make, {
                          children: "Sign in",
                          className: "title"
                        }), React.createElement("div", {
                          className: "signup"
                        }, React.createElement(Typography.$$Text.make, {
                              children: "Don't have an account?"
                            }), JsxUtils.str(" "), React.createElement(Link.make, {
                              children: JsxUtils.str("Sign up"),
                              to: "#"
                            })), React.createElement("form", {
                          className: "form"
                        }, React.createElement(InputText.make, {
                              placeholder: "E-mail",
                              value: "",
                              onChange: (function (prim) {
                                  console.log(prim);
                                  
                                })
                            }), React.createElement(InputPassword.make, {
                              className: "-mt",
                              placeholder: "Password",
                              value: "",
                              onChange: (function (prim) {
                                  console.log(prim);
                                  
                                })
                            }), React.createElement(Button.make, {
                              children: "Sign in",
                              className: "-mt"
                            })), React.createElement("div", {
                          className: "skip"
                        }, React.createElement(Typography.$$Text.make, {
                              children: "Skip sign-in for now and"
                            }), JsxUtils.str(" "), React.createElement(Link.make, {
                              children: JsxUtils.str("start reading"),
                              to: "#"
                            })))));
}

var make = SignInPage;

export {
  Styles ,
  make ,
  
}
/* form Not a pure module */
