// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxUtils from "../utils/JsxUtils.bs.js";

function Button(Props) {
  var children = Props.children;
  var className = Props.className;
  return React.createElement("button", {
              className: JsxUtils.classNames("button", className)
            }, JsxUtils.str(children));
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
