// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Person_black_24dpSvg from "../assets/person_black_24dp.svg";

var make = Person_black_24dpSvg.ReactComponent;

var Person = {
  make: make
};

function Icon(Props) {
  var className = Props.className;
  var cssClasses = className !== undefined ? "icon " + className : "icon";
  return React.createElement(make, {
              className: cssClasses
            });
}

var make$1 = Icon;

export {
  Person ,
  make$1 as make,
  
}
/* make Not a pure module */
