// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxUtils from "../utils/JsxUtils.bs.js";

function InputText(Props) {
  var className = Props.className;
  var placeholderOpt = Props.placeholder;
  var value = Props.value;
  var onChange = Props.onChange;
  var placeholder = placeholderOpt !== undefined ? placeholderOpt : "";
  return React.createElement("input", {
              className: JsxUtils.classNames("input", className),
              placeholder: placeholder,
              value: value,
              onChange: onChange
            });
}

var make = InputText;

export {
  make ,
  
}
/* react Not a pure module */
