// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxUtils from "../utils/JsxUtils.bs.js";

function Link(Props) {
  var className = Props.className;
  var children = Props.children;
  var to = Props.to;
  return React.createElement("a", {
              className: JsxUtils.classNames("link", className),
              href: to
            }, children);
}

var make = Link;

export {
  make ,
  
}
/* react Not a pure module */
