// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LogoSvg from "../assets/logo.svg";

var make = LogoSvg.ReactComponent;

var RawComponent = {
  make: make
};

function Logo(Props) {
  var whiteOpt = Props.white;
  var white = whiteOpt !== undefined ? whiteOpt : false;
  var $$class = white ? "logo" : "logo -black";
  return React.createElement(make, {
              className: $$class
            });
}

var make$1 = Logo;

export {
  RawComponent ,
  make$1 as make,
  
}
/* make Not a pure module */
