// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function getTargetValue(setter, $$event) {
  var value = $$event.currentTarget.value;
  return Curry._1(setter, (function (param) {
                return value;
              }));
}

function str(prim) {
  return prim;
}

export {
  getTargetValue ,
  str ,
  
}
/* No side effect */
