// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function getValue(setter, $$event) {
  var value = $$event.currentTarget.value;
  return Curry._1(setter, (function (param) {
                return value;
              }));
}

export {
  getValue ,
  
}
/* No side effect */
