// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Feed from "./pages/Feed.bs.js";
import * as React from "react";

import './styles/index.scss'
;

function App(Props) {
  return React.createElement(Feed.make, {});
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
