// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as Button from "./components/button/Button.bs.js";

Theme.setGlobalStyles(undefined);

function App(Props) {
  return React.createElement(Button.make, {
              children: "Sign in"
            });
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
