// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var elementId = "#root";

var maybeRootElement = document.querySelector(elementId);

if (maybeRootElement == null) {
  console.log("$elementId element not found");
} else {
  ReactDom.render(React.createElement("h1", undefined, "Hello from rescript"), maybeRootElement);
}

var maybeRootElement$1 = (maybeRootElement == null) ? undefined : Caml_option.some(maybeRootElement);

export {
  elementId ,
  maybeRootElement$1 as maybeRootElement,
  
}
/* maybeRootElement Not a pure module */
