// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

var Colors = {
  primary: "477bff",
  primary50: "ebf0ff",
  black: "131128",
  white: "fff",
  neutral: "282c3c",
  neutral200: "aeb3c9"
};

var family = {
  NAME: "custom",
  VAL: "'DM Sans', sans-serif"
};

var size = CssJs.px(20);

var Font = {
  family: family,
  size: size
};

var small = CssJs.px(6);

var medium = CssJs.px(12);

var large = CssJs.px(16);

var Radius = {
  small: small,
  medium: medium,
  large: large
};

function setGlobalStyles(param) {
  return CssJs.$$global("html", [
              CssJs.fontFamily(family),
              CssJs.fontSize(size)
            ]);
}

export {
  Colors ,
  Font ,
  Radius ,
  setGlobalStyles ,
  
}
/* size Not a pure module */
