// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

var from_0 = CssJs.pct(0.0);

var from_1 = CssJs.hex("477bff");

var from = [
  from_0,
  from_1
];

var to_0 = CssJs.pct(100.0);

var to_1 = CssJs.hex("306aff");

var to = [
  to_0,
  to_1
];

var BlueGradient = {
  from: from,
  to: to
};

var Colors = {
  primary50: "ebf0ff",
  primary300: "5786ff",
  black: "131128",
  white: "fff",
  neutral: "282c3c",
  neutral200: "aeb3c9",
  BlueGradient: BlueGradient
};

var family = {
  NAME: "custom",
  VAL: "'DM Sans', sans-serif"
};

var size = CssJs.px(20);

var Font = {
  family: family,
  size: size
};

var small = CssJs.px(6);

var medium = CssJs.px(12);

var large = CssJs.px(16);

var Radius = {
  small: small,
  medium: medium,
  large: large
};

function setGlobalStyles(param) {
  return CssJs.$$global("html", [
              CssJs.fontFamily(family),
              CssJs.fontSize(size)
            ]);
}

export {
  Colors ,
  Font ,
  Radius ,
  setGlobalStyles ,
  
}
/* from Not a pure module */
