// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../Theme.bs.js";
import * as React from "react";

var link = CssJs.style([
      CssJs.borderBottom(CssJs.px(2), CssJs.solid, CssJs.hex(Theme.Colors.primary300)),
      CssJs.color(CssJs.hex(Theme.Colors.primary300)),
      CssJs.textDecoration(CssJs.none),
      CssJs.letterSpacing({
            NAME: "rem",
            VAL: -0.04
          })
    ]);

var Styles = {
  link: link
};

function Link(Props) {
  var children = Props.children;
  var to = Props.to;
  return React.createElement("a", {
              className: link,
              href: to
            }, children);
}

var make = Link;

export {
  Styles ,
  make ,
  
}
/* link Not a pure module */
